name: build app with yarn
on:
  push:
    branches: ["action"]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: npm install --global yarn
      - name: Install dependency
        run: yarn install
      - name: Build vue application
        run: yarn build
      - name: Archive artifact
        run: tar --directory dist -cf "$RUNNER_TEMP/artifact.tar" .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: vindictus-partholon-vanguard
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ github.retention_days }}
          if-no-files-found: error
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: vindictus-partholon-vanguard
